apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "coordinating"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.coordinating.fullname" . }}
{{- if .Values.coordinating.serviceAnnotations }}
  annotations:
{{ toYaml .Values.coordinating.serviceAnnotations | indent 4 }}
{{- end }}

spec:
  ports:
    - name: http
      port: 9200
      targetPort: http
  selector:
    app: {{ template "elasticsearch.name" . }}
    component: "coordinating"
    release: {{ .Release.Name }}
  type: {{ .Values.coordinating.serviceType }}
