apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "coordinating"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.coordinating.fullname" . }}
{{- if .Values.coordinating.serviceAnnotations }}
  annotations:
  {{- range $key, $value := .Values.coordinating.serviceAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  ports:
    - name: http
      port: 9200
      targetPort: http
  selector:
    app: {{ template "elasticsearch.name" . }}
    component: "coordinating"
    release: {{ .Release.Name }}
  type: "{{ .Values.coordinating.service.type }}"
{{- if contains "NodePort" .Values.coordinating.service.type }}
  {{- if .Values.coordinating.service.nodePort }}
      nodePort:  {{ .Values.coordinating.service.nodePort }}
  {{- end }}
{{- end }}
{{- if .Values.coordinating.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.coordinating.service.externalIPs | indent 4 }}
{{- end }}
{{- if eq "ClusterIP" .Values.coordinating.service.type }}
  {{- if .Values.coordinating.service.clusterIP }}
  clusterIP:  {{ .Values.coordinating.service.clusterIP }}
  {{- end }}
{{- end }}
{{- if eq "LoadBalancer" .Values.coordinating.service.type }}
  {{- if .Values.coordinating.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.coordinating.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.coordinating.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.coordinating.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}